// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppEnvios.Data;

#nullable disable

namespace WebAppEnvios.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAppEnvios.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ClienteId");

                    b.HasIndex("Email");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("WebAppEnvios.Models.WebAppEnvios.Models.Destinatario", b =>
                {
                    b.Property<int>("DestinatarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestinatarioId"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinatarioId");

                    b.ToTable("Destinatarios");
                });

            modelBuilder.Entity("WebAppEnvios.Models.WebAppEnvios.Models.Envio", b =>
                {
                    b.Property<int>("EnvioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnvioId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DestinatarioId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.HasKey("EnvioId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DestinatarioId");

                    b.HasIndex("EstadoId");

                    b.ToTable("Envios");
                });

            modelBuilder.Entity("WebAppEnvios.Models.WebAppEnvios.Models.EstadoEnvio", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstadoId");

                    b.ToTable("EstadosEnvio");
                });

            modelBuilder.Entity("WebAppEnvios.Models.WebAppEnvios.Models.Paquete", b =>
                {
                    b.Property<int>("PaqueteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaqueteId"));

                    b.Property<int>("EnvioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PaqueteId");

                    b.HasIndex("EnvioId");

                    b.ToTable("Paquetes");
                });

            modelBuilder.Entity("WebAppEnvios.Models.WebAppEnvios.Models.Envio", b =>
                {
                    b.HasOne("WebAppEnvios.Models.Cliente", "Cliente")
                        .WithMany("Envios")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAppEnvios.Models.WebAppEnvios.Models.Destinatario", "Destinatario")
                        .WithMany("Envios")
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebAppEnvios.Models.WebAppEnvios.Models.EstadoEnvio", "EstadoEnvio")
                        .WithMany("Envios")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Destinatario");

                    b.Navigation("EstadoEnvio");
                });

            modelBuilder.Entity("WebAppEnvios.Models.WebAppEnvios.Models.Paquete", b =>
                {
                    b.HasOne("WebAppEnvios.Models.WebAppEnvios.Models.Envio", "Envio")
                        .WithMany("Paquetes")
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Envio");
                });

            modelBuilder.Entity("WebAppEnvios.Models.Cliente", b =>
                {
                    b.Navigation("Envios");
                });

            modelBuilder.Entity("WebAppEnvios.Models.WebAppEnvios.Models.Destinatario", b =>
                {
                    b.Navigation("Envios");
                });

            modelBuilder.Entity("WebAppEnvios.Models.WebAppEnvios.Models.Envio", b =>
                {
                    b.Navigation("Paquetes");
                });

            modelBuilder.Entity("WebAppEnvios.Models.WebAppEnvios.Models.EstadoEnvio", b =>
                {
                    b.Navigation("Envios");
                });
#pragma warning restore 612, 618
        }
    }
}
